# Generated by Django 5.2 on 2025-05-01 15:46

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorldCup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('host', models.CharField(max_length=100)),
                ('champion', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='worldcups/')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='players/')),
                ('bio', ckeditor.fields.RichTextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='blog.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='worldcup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='blog.worldcup'),
        ),
    ]
